accession_id_prefix: AITXXX
author: https://orcid.org/0000-0003-3373-7386
description: 'Cellular and molecular characterization of human cortical cytoarchitecture.
  Supercluster: Non-neuronal cells.'
github_org: hkir-dev
id: CCN20240304
matrix_file_id: CellXGene_dataset:5346f9c6-755e-4336-94cc-38706ec00c2f
repo: human-neocortex-non-neuronal-cells
title: 'Supercluster: Non-neuronal cells'
